# Generated by Django 4.0.2 on 2022-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(default='profile/filename.jpg', null=True, upload_to='profile'),
        ),
    ]
