# Generated by Django 4.0.2 on 2022-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_skills_id_alter_user_user_role_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_site',
            name='face_book',
            field=models.CharField(default='facebook.com', max_length=150),
        ),
        migrations.AddField(
            model_name='work_site',
            name='linked_in',
            field=models.CharField(default='linkedin.com', max_length=150),
        ),
    ]
