# Generated by Django 4.0.2 on 2022-03-05 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_work_site_face_book_work_site_linked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_site',
            name='user_work_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
