# Generated by Django 4.0.2 on 2022-03-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_work_site_user_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_site',
            name='face_book',
            field=models.CharField(blank=True, default='facebook.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='work_site',
            name='link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='work_site',
            name='linked_in',
            field=models.CharField(blank=True, default='linkedin.com', max_length=150),
        ),
    ]
